# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tel', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('education', models.CharField(max_length=20)),
                ('academy', models.CharField(max_length=30)),
                ('hobby', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.BooleanField()),
                ('tel', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to=b'')),
                ('title', models.CharField(max_length=20)),
                ('academy', models.CharField(max_length=30)),
                ('research', models.CharField(max_length=100, null=True)),
                ('hobby', models.CharField(max_length=100, null=True)),
                ('tag', models.BooleanField()),
            ],
        ),
    ]
