# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherManage', '0004_auto_20161117_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.IntegerField()),
                ('student', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
                ('student_email', models.EmailField(max_length=254)),
                ('teacher_email', models.EmailField(max_length=254)),
                ('topic', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
