# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherManage', '0006_auto_20161215_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tag',
            field=models.IntegerField(null=True),
        ),
    ]
