# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherManage', '0007_appointment_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tag',
            field=models.IntegerField(default=0),
        ),
    ]
