# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherManage', '0008_auto_20161215_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tag',
            field=models.IntegerField(default=-1),
        ),
    ]
